# Numpy tips

In [3]:
import numpy as np

## Indexing, arrya/nd-array construction

Basic operations

In [4]:
x = np.array([1, 2, 3, 4])

NumPy uses zero-base indexing system:

In [5]:
print("First element of the array is: ", x[0])

First element of the array is:  1


## Attributes of a NumPy array

In [8]:
x.ndim # the number of dimensions

1

In [9]:
x.size # the number of items in array

4

In [10]:
x.shape # shape of an array

(4,)

In [11]:
x.itemsize # the number of byte per element

8

In [27]:
x.dtype # underlying data type (there are many useful data types are came with numpy)

dtype('int64')

In [ ]:
x.data # memoryview of the underlying data

## Array creation

There are several commonly used functions to create arrays using numpy:
  * np.zeros  - creates arrays filled with zero values;
  * np.ones   - create array filled with unity values;
  * np.arange - create array of equal stated values, e.g. 1,2,3,4,5 ... 
  * np.linspace - create array of equal stated values, based on specified interval, e.g. [a,..,b] divided into n equal spaces;
  * np.empty   - creates of uninitialized array of desired shape
  * np.ones_like - creates array of unity values based on provided template array 
  * np.zeros_like - creates array of zero values based on provided template array
  * np.empty_like - creates unintialized array of specified shape (shape is getting from provided template)
  * np.full_like - creates array using template array and fills it with specified value
  * np.full - creates array of specified shape and fills it with specified value 

In [16]:
zeros = np.zeros((3, 3)) # make 3x3 array of zeros
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
ones = np.ones((3, 3, 3)) #make 3x3x3 array of ones
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [35]:
np.full((3, 4), 10) # creates array of 3(rows)x4(columns) shape and fills it with 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [24]:
np.empty_like([3,4]) # Note: the function returns unintialized array!

array([140685384578728,        57513600])

In [25]:
np.empty_like(ones) # This doesn't guarantee that function always will return array of unity values

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
np.full_like(ones, 3) # Make an array using template `ones` (shape=3x3x3) and fill it with 3

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [26]:
np.empty((4,5)) # just empty (uninitialized) array; it filled with arbitrary values of floats

array([[6.95078154e-310, 2.83326727e-316, 0.00000000e+000,
        0.00000000e+000, 6.95059721e-310],
       [1.50008929e+248, 4.50620083e-144, 6.18620730e+223,
        4.90922082e+252, 4.54814392e-144],
       [5.22689326e-143, 1.26189133e-076, 2.42196513e-028,
        1.42516747e-071, 4.50615868e-144],
       [1.16096445e-028, 8.75410241e+169, 2.32784209e-057,
        6.23467717e+174, 7.78822384e-071]])

###  Building arrays of equally spaced values

In [28]:
np.arange(1, 100) # values from 1 to 99 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
np.arange(1, 10, 0.2) # equally spaced values with specified step

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [32]:
# Note: no error occurs, just empty array. We cannot create array since start value is greater the end value
np.arange(10, 1, 0.2) 

array([], dtype=float64)

In [33]:
np.linspace(1, 10, 10) # ten values between [1, 10] including bounding values; this is useful when plotting graphs

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Randomly generated arrays

NumPy has a random submodule that provides facilities to fill multidimensional arrays with randomly (with specified distribution) generated values.

This submodule includes:

   * np.random.rand  - generates uniformly distributed values of specified shape
   * np.random.randn - generates normally distributed values of specified shape
   * np.random.seed - sets state to generator of random values (this is very important to get reproducible results)


In [42]:
np.random.rand(3, 3) # creates 3x3 matrix of random values sampled (uniform distribution is used) from [0, 1) 

array([[0.2817105 , 0.66649299, 0.39358211],
       [0.70242927, 0.42650531, 0.6176062 ],
       [0.24889633, 0.28047364, 0.26109473]])

In [43]:
np.random.randn(3, 3) # creates 3x3 matrix of random values sampled (standard normal distribution is used)

array([[-1.4042995 , -0.35858491, -0.04182134],
       [-0.55933912,  0.5357998 ,  0.7640853 ],
       [-0.52310893, -0.50609971,  0.3018963 ]])

In [50]:
np.random.seed(23) # sets state of random generator; this makes further results reproducible