# Numpy tips

In [1]:
import numpy as np

## Indexing, arrya/nd-array construction

Basic operations

In [2]:
x = np.array([1, 2, 3, 4])

NumPy uses zero-base indexing system:

In [3]:
print("First element of the array is: ", x[0])

First element of the array is:  1


## Attributes of a NumPy array

In [4]:
x.ndim # the number of dimensions

1

In [5]:
x.size # the number of items in array

4

In [6]:
x.shape # shape of an array

(4,)

In [7]:
x.itemsize # the number of byte per element

8

In [8]:
x.dtype # underlying data type (there are many useful data types are came with numpy)

dtype('int64')

In [9]:
x.data # memoryview of the underlying data

## Array creation

There are several commonly used functions to create arrays using numpy:
  * np.zeros  - creates arrays filled with zero values;
  * np.ones   - create array filled with unity values;
  * np.arange - create array of equal stated values, e.g. 1,2,3,4,5 ... 
  * np.linspace - create array of equal stated values, based on specified interval, e.g. [a,..,b] divided into n equal spaces;
  * np.empty   - creates of uninitialized array of desired shape
  * np.ones_like - creates array of unity values based on provided template array 
  * np.zeros_like - creates array of zero values based on provided template array
  * np.empty_like - creates unintialized array of specified shape (shape is getting from provided template)
  * np.full_like - creates array using template array and fills it with specified value
  * np.full - creates array of specified shape and fills it with specified value 
  * np.fromfunction - creates array using specified function to fill it with values

In [10]:
zeros = np.zeros((3, 3)) # make 3x3 array of zeros
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
ones = np.ones((3, 3, 3)) #make 3x3x3 array of ones
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
np.full((3, 4), 10) # creates array of 3(rows)x4(columns) shape and fills it with 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [13]:
np.empty_like([3,4]) # Note: the function returns unintialized array!

array([140136196851400, 140136196851400])

In [14]:
np.empty_like(ones) # This doesn't guarantee that function always will return array of unity values

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.full_like(ones, 3) # Make an array using template `ones` (shape=3x3x3) and fill it with 3

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [16]:
np.empty((4,5)) # just empty (uninitialized) array; it filled with arbitrary values of floats

array([[6.92364806e-310, 2.56674218e-316, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        3.21142670e-322, 6.92364806e-310],
       [2.56674771e-316, 2.57368597e-316, 6.92364806e-310,
        0.00000000e+000, 0.00000000e+000]])

###  Building arrays of equally spaced values

In [17]:
np.arange(1, 100) # values from 1 to 99 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
np.arange(1, 10, 0.2) # equally spaced values with specified step

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [19]:
# Note: no error occurs, just empty array. We cannot create array since start value is greater the end value
np.arange(10, 1, 0.2) 

array([], dtype=float64)

In [20]:
np.linspace(1, 10, 10) # ten values between [1, 10] including bounding values; this is useful when plotting graphs

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.fromfunction(lambda x, y: x + y, (2,2))

array([[0., 1.],
       [1., 2.]])

In [22]:
np.fromfunction(lambda x, y, z: x + y + z, shape=(3, 2, 3))

array([[[0., 1., 2.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [2., 3., 4.]],

       [[2., 3., 4.],
        [3., 4., 5.]]])

### Randomly generated arrays

NumPy has a random submodule that provides facilities to fill multidimensional arrays with randomly (with specified distribution) generated values.

This submodule includes:

   * np.random.rand  - generates uniformly distributed values of specified shape
   * np.random.randn - generates normally distributed values of specified shape
   * np.random.seed - sets state to generator of random values (this is very important to get reproducible results)


In [23]:
np.random.rand(3, 3) # creates 3x3 matrix of random values sampled (uniform distribution is used) from [0, 1) 

array([[0.91628839, 0.56166571, 0.60434142],
       [0.06857474, 0.02912602, 0.1046682 ],
       [0.66780772, 0.47240026, 0.67085425]])

In [24]:
np.random.randn(3, 3) # creates 3x3 matrix of random values sampled (standard normal distribution is used)

array([[-1.07993565,  0.54783463,  1.1816294 ],
       [-0.58096758, -0.3790252 , -0.12691865],
       [-0.38423608,  1.2390727 , -0.57433342]])

In [25]:
np.random.seed(23) # sets state of random generator; this makes further results reproducible

## Universal functions

Universal functions operate elementwise and could be applyed to numpy arrays. These functions produce arryas of the same shape as input ones. 

    * np.sin
    * np.cos
    * np.tan
    * np.arcsin
    * np.arccos
    * np.arctan
    * np.sqrt
    * np.power
    * np.exp
    
    * np.frompyfunc

In [26]:
data = np.array([1, 2, 3])

In [27]:
np.sin(data)

array([0.84147098, 0.90929743, 0.14112001])

In [28]:
np.cos(data)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [29]:
z=np.frompyfunc(lambda x: x ** 2, 1, 1) # That is useful to produce vectorized version of a function

### Array advanced indexing / Block manipulation

    * np.c_
    * np.r_
    * np.column_stack
    * np.hstack
    * np.row_stack
    * p. vstack
    * np.dstack

In [30]:
z = np.random.rand(3,10)

In [31]:
z.shape

(3, 10)

In [32]:
z.resize(10,3) # .resize modified array itself

In [33]:
z.shape

(10, 3)

In [34]:
z.reshape(3, 10).shape # .reshape retruns modified array; this function doesn't change the input data

(3, 10)

In [35]:
z.shape

(10, 3)

In [36]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [37]:
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [38]:
np.vstack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.c_[x, y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
np.r_[x, y]

array([1, 2, 3, 4, 5, 6])

In [41]:
np.column_stack([x, y])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
np.row_stack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.dstack([x, y, x])

array([[[1, 4, 1],
        [2, 5, 2],
        [3, 6, 3]]])

In [44]:
np.concatenate([x, y], axis=0)

array([1, 2, 3, 4, 5, 6])

In [45]:
w = np.random.rand(3, 4)
v = np.random.rand(3, 4)

In [46]:
np.dstack([v,w]).shape 

(3, 4, 2)

In [47]:
np.stack([v, w]).shape # See the difference in shapes when applying dstack and stack

(2, 3, 4)

In [48]:
np.concatenate([v, w], axis=1).shape

(3, 8)

In [49]:
np.concatenate([v, w], axis=0).shape  # Be care regardin axis argument... 

(6, 4)

In [50]:
np.concatenate([v, w], axis=None).shape  # when axis=None, arrays are flattened before concatenation

(24,)

In [51]:
z = np.arange(100)

In [52]:
np.split(v, 2, axis=1)  # This function raise an Exception when the array couldn't be splitted to equal parts

[array([[0.65584546, 0.55770676],
        [0.50605463, 0.3967457 ],
        [0.90160219, 0.50575932]]), array([[0.17824727, 0.24058353],
        [0.48305519, 0.95573984],
        [0.82070149, 0.82771593]])]

In [53]:
np.array_split(v, 2)  # This function doesn't raise an Exception when the array couldn't be splitted to equal parts

[array([[0.65584546, 0.55770676, 0.17824727, 0.24058353],
        [0.50605463, 0.3967457 , 0.48305519, 0.95573984]]),
 array([[0.90160219, 0.50575932, 0.82070149, 0.82771593]])]

### Some commonly used functions

In [54]:
sample = np.random.rand(5, 4)

### Using `np.where`

In [69]:
for i, j in zip(*np.where(sample>0.9)):
    print(sample[i, j])

0.9179458057039298
0.9164077220658395
0.9515877600012642
0.9725177804264937


In [71]:
# Leave only values that are greater than 0.9
np.where(sample>0.9, sample, 0)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.91794581, 0.        ],
       [0.91640772, 0.        , 0.        , 0.95158776],
       [0.        , 0.        , 0.97251778, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [78]:
# Change values that fall in [0.1, 0.9] interval
np.where((sample > 0.9)|(sample < 0.1), sample, -1)

array([[-1.        ,  0.07905549, -1.        , -1.        ],
       [-1.        , -1.        ,  0.91794581, -1.        ],
       [ 0.91640772, -1.        , -1.        ,  0.95158776],
       [-1.        , -1.        ,  0.97251778, -1.        ],
       [-1.        , -1.        , -1.        , -1.        ]])

### Using `np.choose`

In [83]:
list(np.ndindex((2,2)))

[(0, 0), (0, 1), (1, 0), (1, 1)]

In [158]:
what = np.array([0, 2, 0, 0, 0])
choices = np.arange(3 * 4 * 5).reshape(3, 4, 5)

In [162]:
choices

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [165]:
choices[2][1]

array([45, 46, 47, 48, 49])

In [160]:
np.choose(what, choices)

array([[ 0, 41,  2,  3,  4],
       [ 5, 46,  7,  8,  9],
       [10, 51, 12, 13, 14],
       [15, 56, 17, 18, 19]])

In [134]:
np.array([c[a[I]][I] for I in np.ndindex((4,))])

array([20, 31, 12,  3])

In [115]:
list(np.ndindex((4,2)))

[(0, 0), (0, 1), (1, 0), (1, 1), (2, 0), (2, 1), (3, 0), (3, 1)]