# Numpy tips

In [2]:
import numpy as np

## Indexing, arrya/nd-array construction

Basic operations

In [3]:
x = np.array([1, 2, 3, 4])

NumPy uses zero-base indexing system:

In [4]:
print("First element of the array is: ", x[0])

First element of the array is:  1


## Attributes of a NumPy array

In [5]:
x.ndim # the number of dimensions

1

In [6]:
x.size # the number of items in array

4

In [7]:
x.shape # shape of an array

(4,)

In [8]:
x.itemsize # the number of byte per element

8

In [9]:
x.dtype # underlying data type (there are many useful data types are came with numpy)

dtype('int64')

In [10]:
x.data # memoryview of the underlying data

## Array creation

There are several commonly used functions to create arrays using numpy:
  * np.zeros  - creates arrays filled with zero values;
  * np.ones   - create array filled with unity values;
  * np.arange - create array of equal stated values, e.g. 1,2,3,4,5 ... 
  * np.linspace - create array of equal stated values, based on specified interval, e.g. [a,..,b] divided into n equal spaces;
  * np.empty   - creates of uninitialized array of desired shape
  * np.ones_like - creates array of unity values based on provided template array 
  * np.zeros_like - creates array of zero values based on provided template array
  * np.empty_like - creates unintialized array of specified shape (shape is getting from provided template)
  * np.full_like - creates array using template array and fills it with specified value
  * np.full - creates array of specified shape and fills it with specified value 
  * np.fromfunction - creates array using specified function to fill it with values

In [11]:
zeros = np.zeros((3, 3)) # make 3x3 array of zeros
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
ones = np.ones((3, 3, 3)) #make 3x3x3 array of ones
print(ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
np.full((3, 4), 10) # creates array of 3(rows)x4(columns) shape and fills it with 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [14]:
np.empty_like([3,4]) # Note: the function returns unintialized array!

array([139658003261128, 139658003261128])

In [15]:
np.empty_like(ones) # This doesn't guarantee that function always will return array of unity values

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
np.full_like(ones, 3) # Make an array using template `ones` (shape=3x3x3) and fill it with 3

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [17]:
np.empty((4,5)) # just empty (uninitialized) array; it filled with arbitrary values of floats

array([[6.90002216e-310, 2.82800330e-316, 0.00000000e+000,
        0.00000000e+000, 6.89988151e-310],
       [1.50008929e+248, 4.50620083e-144, 6.18620730e+223,
        4.90922082e+252, 4.54814392e-144],
       [5.22689326e-143, 1.26189133e-076, 2.42295120e-028,
        4.17636286e-062, 4.50615877e-144],
       [1.16096445e-028, 9.77593026e+165, 2.34147439e-057,
        1.68686408e-051, 1.39497374e-047]])

###  Building arrays of equally spaced values

In [18]:
np.arange(1, 100) # values from 1 to 99 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
np.arange(1, 10, 0.2) # equally spaced values with specified step

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [20]:
# Note: no error occurs, just empty array. We cannot create array since start value is greater the end value
np.arange(10, 1, 0.2) 

array([], dtype=float64)

In [21]:
np.linspace(1, 10, 10) # ten values between [1, 10] including bounding values; this is useful when plotting graphs

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.fromfunction(lambda x, y: x + y, (2,2))

array([[0., 1.],
       [1., 2.]])

In [26]:
np.fromfunction(lambda x, y, z: x + y + z, shape=(3, 2, 3))

array([[[0., 1., 2.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [2., 3., 4.]],

       [[2., 3., 4.],
        [3., 4., 5.]]])

### Randomly generated arrays

NumPy has a random submodule that provides facilities to fill multidimensional arrays with randomly (with specified distribution) generated values.

This submodule includes:

   * np.random.rand  - generates uniformly distributed values of specified shape
   * np.random.randn - generates normally distributed values of specified shape
   * np.random.seed - sets state to generator of random values (this is very important to get reproducible results)


In [42]:
np.random.rand(3, 3) # creates 3x3 matrix of random values sampled (uniform distribution is used) from [0, 1) 

array([[0.2817105 , 0.66649299, 0.39358211],
       [0.70242927, 0.42650531, 0.6176062 ],
       [0.24889633, 0.28047364, 0.26109473]])

In [43]:
np.random.randn(3, 3) # creates 3x3 matrix of random values sampled (standard normal distribution is used)

array([[-1.4042995 , -0.35858491, -0.04182134],
       [-0.55933912,  0.5357998 ,  0.7640853 ],
       [-0.52310893, -0.50609971,  0.3018963 ]])

In [50]:
np.random.seed(23) # sets state of random generator; this makes further results reproducible

## Universal functions

Universal functions operate elementwise and could be applyed to numpy arrays. These functions produce arryas of the same shape as input ones. 

    * np.sin
    * np.cos
    * np.tan
    * np.arcsin
    * np.arccos
    * np.arctan
    * np.sqrt
    * np.power
    * np.exp
    
    * np.frompyfunc

In [31]:
data = np.array([1, 2, 3])

In [32]:
np.sin(data)

array([0.84147098, 0.90929743, 0.14112001])

In [33]:
np.cos(data)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [35]:
z=np.frompyfunc(lambda x: x ** 2, 1, 1) # That is useful to produce vectorized version of a function

### Array advanced indexing / Block manipulation

    * np.c_
    * np.r_
    * np.column_stack
    * np.hstack
    * np.row_stack
    * p. vstack
    * np.dstack

In [39]:
z = np.random.rand(3,10)

In [41]:
z.shape

(3, 10)

In [42]:
z.resize(10,3) # .resize modified array itself

In [44]:
z.shape

(10, 3)

In [46]:
z.reshape(3, 10).shape # .reshape retruns modified array; this function doesn't change the input data

(3, 10)

In [47]:
z.shape

(10, 3)

In [64]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [65]:
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [66]:
np.vstack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.c_[x, y]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
np.r_[x, y]

array([1, 2, 3, 4, 5, 6])

In [69]:
np.column_stack([x, y])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
np.row_stack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.dstack([x, y, x])

array([[[1, 4, 1],
        [2, 5, 2],
        [3, 6, 3]]])

In [73]:
np.concatenate([x, y], axis=0)

array([1, 2, 3, 4, 5, 6])

In [81]:
w = np.random.rand(3, 4)
v = np.random.rand(3, 4)

In [89]:
np.dstack([v,w]).shape 

(3, 4, 2)

In [92]:
np.stack([v, w]).shape # See the difference in shapes when applying dstack and stack

(2, 3, 4)

In [97]:
np.concatenate([v, w], axis=1).shape

(3, 8)

In [98]:
np.concatenate([v, w], axis=0).shape  # Be care regardin axis argument... 

(6, 4)

In [99]:
np.concatenate([v, w], axis=None).shape  # when axis=None, arrays are flattened before concatenation

(24,)

In [100]:
z = np.arange(100)

In [108]:
np.split(v, 2, axis=1)  # This function raise an Exception when the array couldn't be splitted to equal parts

[array([[0.68555028, 0.90555011],
        [0.18278129, 0.64646553],
        [0.27458846, 0.57650764]]), array([[0.67605818, 0.94011026],
        [0.60858848, 0.90469509],
        [0.77678714, 0.27891043]])]

In [110]:
np.array_split(v, 2)  # This function doesn't raise an Exception when the array couldn't be splitted to equal parts

[array([[0.68555028, 0.90555011, 0.67605818, 0.94011026],
        [0.18278129, 0.64646553, 0.60858848, 0.90469509]]),
 array([[0.27458846, 0.57650764, 0.77678714, 0.27891043]])]