## Problems and their solutions using NumPy

### Content

 1. Indices of groups with same value (islands of homoheneity)
 2. Indices of first occurences

#### Module importing 

In [18]:
import numpy as np

In [19]:
# 1
y=[1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,1]
np.flatnonzero(np.diff(np.r_[0,y,0])!=0).reshape(-1,2) - [0,1]

array([[ 0,  2],
       [ 8,  9],
       [16, 19]])

\# 2

Suppose we have a data frame and need to find occurences of specified set of elements in a column of that data frame. In this case pd.Series.searchsorted is a good choice.

In [7]:
# 2
import numpy as np
import pandas as pd
data = pd.DataFrame({'x': [1, 1, 1, 3, 3, 4, 5]})
values = [1, 3, 4, 5]
common_values = np.intersect1d(data.x.values, values)
print(common_values)
print(data.x.searchsorted(common_values))
print(data.loc[data.x.searchsorted(common_values)])

[1 3 4 5]
[0 3 5 6]
   x
0  1
3  3
5  4
6  5


\# 3. Based on https://gist.github.com/nlintz/f5bde5df8eee57472954


Convert an image to a set of patches and back again.

In [ ]:
import numpy as np 
from skimage.util import view_as_blocks

def image_to_patches(img, patch_shape):
    """
        converts an image into M patch_shaped chunks
        arguments --
        img: [rows, cols, nchannels]
        patch_shape: (rows, cols, nchannels)
        returns --
        [M, patch_shape[0], patch_shape[1], nchannels]
    """

    blocks = view_as_blocks(img, patch_shape)
    return blocks.reshape((-1,) + patch_shape, order="F")


def patches_to_image(patches, patch_shape, img_shape):
    """
        converts result from image_to_patches back into an image of the
        original image's shape
        patches: [n_patches, rows, cols, nchannels]
        patch_shape: (rows, cols, nchannels)
        img_shape: (rows, cols, nchannels)
    """

    patches_per_col = img_shape[0] // patch_shape[0]
    res = []
    for i in range(0, patches_per_col):
        res.append(np.concatenate(patches[i::patches_per_col], axis=1))
    return np.array(res)