In [19]:
import pandas as pd
import numpy as np
train = pd.read_csv("./data/train.csv")
test = pd.read_csv("./data/test.csv")
from string import punctuation
from utils import get_family_size, parse_name, get_cabin_letter
combined = pd.concat([train, test]).reset_index(drop=True)


In [2]:
combined.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket  
0       3    male      1       0.0         A/5 21171  
1       1  female      1       1.0          PC 17599  
2       3  female      0       1.0  STON/O2. 3101282  
3       1  female      1       1.0            113803  
4       3    male      0       0.0            373450

In [3]:
combined = get_cabin_letter(combined)

In [4]:
combined.head()

Age Cabin Embarked     Fare  \
0  22.0     0        S   7.2500   
1  38.0     C        C  71.2833   
2  26.0     0        S   7.9250   
3  35.0     C        S  53.1000   
4  35.0     0        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket  Cabin_nan  
0       3    male      1       0.0         A/5 21171        1.0  
1       1  female      1       1.0          PC 17599        0.0  
2       3  female      0       1.0  STON/O2. 3101282        1.0  
3       1  female      1       1.0            113803        0.0  
4       3    male      0       0.0            373450        1.0

In [7]:
pd.DataFrame({'x':[1,2], '_x':[4,5]}, columns=['x', '_x'])


x  _x
0  1   4
1  2   5

In [39]:
from imblearn.under_sampling import TomekLinks

In [40]:
tl = TomekLinks()
null_check = ~pd.isnull(combined.loc[:, ['Fare', 'Age']]).sum(axis=1).astype(np.bool)
y = [1]*train.shape[0] + [0]*test.shape[0]
y = np.array(y)[null_check]
tl.fit_resample(combined.loc[null_check,['Fare', 'Age']], y)

(array([[  7.25 ,  22.   ],
        [  7.925,  26.   ],
        [ 53.1  ,  35.   ],
        ...,
        [  7.775,  28.   ],
        [108.9  ,  39.   ],
        [  7.25 ,  38.5  ]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   

In [47]:
x = pd.DataFrame({'x':[0,1, None, 1, 1,1, 2,3,1], 'y':[4,4,4,4,None, 6,5,4,4]})

In [49]:
x

x    y
0  0.0  4.0
1  1.0  4.0
2  1.0  4.0
3  1.0  4.0
4  1.0  4.0
5  1.0  6.0
6  2.0  5.0
7  3.0  4.0
8  1.0  4.0

In [50]:
from mlpipes.sampling import sample_like_target

In [51]:
z = pd.DataFrame({'x':['a','b','c', 'a'],'y':['q', None, 'x', 'q']})

In [52]:
pd.get_dummies(z)

x_a  x_b  x_c  y_q  y_x
0    1    0    0    1    0
1    0    1    0    0    0
2    0    0    1    0    1
3    1    0    0    1    0

In [133]:
import matplotlib.pyplot as plt
import numpy as np

from imblearn.under_sampling import TomekLinks, RepeatedEditedNearestNeighbours, EditedNearestNeighbours

rng = np.random.RandomState(18)
X_minority = np.transpose([[1.1, 1.3, 1.15, 0.8, 0.55, 2.1],
                           [1., 1.5, 1.7, 2.5, 0.55, 1.9]])
# majority class
X_majority = np.transpose([[2.1, 2.12, 2.13, 2.14, 2.2, 2.3, 2.5, 2.45],
                           [1.5, 2.1, 2.7, 0.9, 1.0, 1.4, 2.4, 2.9]])
tml = EditedNearestNeighbours(sampling_strategy='all', n_neighbors=1)
a, b = tml.fit_resample(np.vstack((X_minority, X_majority)),
                        np.array([0] * X_minority.shape[0] + [1] * X_majority.shape[0]))
tml.sample_indices_

array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11, 12, 13])

In [134]:
X_majority.shape

(8, 2)

In [135]:
a

array([[1.1 , 1.  ],
       [1.3 , 1.5 ],
       [1.15, 1.7 ],
       [0.8 , 2.5 ],
       [0.55, 0.55],
       [2.1 , 1.5 ],
       [2.13, 2.7 ],
       [2.14, 0.9 ],
       [2.2 , 1.  ],
       [2.3 , 1.4 ],
       [2.5 , 2.4 ],
       [2.45, 2.9 ]])

In [136]:
ww=np.vstack((X_minority, X_majority))

In [137]:
ww[tml.sample_indices_]

array([[1.1 , 1.  ],
       [1.3 , 1.5 ],
       [1.15, 1.7 ],
       [0.8 , 2.5 ],
       [0.55, 0.55],
       [2.1 , 1.5 ],
       [2.13, 2.7 ],
       [2.14, 0.9 ],
       [2.2 , 1.  ],
       [2.3 , 1.4 ],
       [2.5 , 2.4 ],
       [2.45, 2.9 ]])

In [76]:
tml.sample_indices_

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13])